server:
  port:  8080
  servlet:
    session:
      timeout: 720m
  tomcat:
    uri-encoding: utf-8

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    name: mysql-druidpool
    url: jdbc:mysql://localhost:3306/question?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    ##password: 3_LuDaXian
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 5
      max-wait: 1000
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.randian.question.entity
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: simple